# Development environment configuration
# For local development and testing

# AWS Configuration
aws:
  region: "us-east-1"
  profile: "default"  # Use default AWS profile for development

# AgentCore Configuration
agentcore:
  browser_tool_endpoint: "https://agentcore-browser-dev.us-east-1.amazonaws.com"
  api_version: "v1"
  timeout: 60  # Longer timeout for development
  max_retries: 5
  retry_delay: 2.0

# Browser Configuration
browser:
  headless: false  # Show browser for debugging
  viewport_width: 1280
  viewport_height: 720
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  page_load_timeout: 60
  element_timeout: 30
  enable_javascript: true
  enable_images: true
  enable_cookies: true

# LlamaIndex Configuration
llamaindex:
  llm_model: "anthropic.claude-3-haiku-20240307-v1:0"  # Faster model for development
  vision_model: "anthropic.claude-3-haiku-20240307-v1:0"
  temperature: 0.1
  max_tokens: 2048
  verbose: true  # Enable verbose logging for development

# CAPTCHA Configuration
captcha:
  enabled: true
  confidence_threshold: 0.7  # Lower threshold for development
  max_attempts: 5
  attempt_delay: 1.0
  supported_types:
    - "recaptcha_v2"
    - "recaptcha_v3"
    - "hcaptcha"
    - "text"
    - "image"

# Security Configuration
security:
  sanitize_input: true
  validate_credentials: true
  audit_logging: true
  encryption:
    enabled: false  # Disabled for development
  session:
    max_duration: 7200  # 2 hours for development
    idle_timeout: 3600  # 1 hour

# Privacy Configuration
privacy:
  pii_detection: true
  pii_mode: "mask"
  data_retention_days: 7  # Short retention for development
  compliance_reporting: false

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_interval: 30  # More frequent metrics for development
  error_tracking: true
  health_check_interval: 60
  cloudwatch:
    enabled: false  # Disabled for local development
    namespace: "LlamaIndex/AgentCore/Dev"

# Logging Configuration
logging:
  level: "DEBUG"  # Verbose logging for development
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  structured: true
  file:
    enabled: true
    path: "logs/dev/llamaindex_agentcore.log"
    max_size: "50MB"
    backup_count: 3
  console:
    enabled: true
    colorize: true

# Development Configuration
development:
  debug: true
  local_browser_fallback: true  # Enable local browser for testing
  mock_responses: false
  test_data_dir: "tests/data"

# Rate limiting (relaxed for development)
rate_limiting:
  enabled: false
  requests_per_minute: 120
  burst_size: 20