# Staging environment configuration
# For pre-production testing and validation

# AWS Configuration
aws:
  region: "us-east-1"
  profile: "staging"  # Use staging AWS profile

# AgentCore Configuration
agentcore:
  browser_tool_endpoint: "https://agentcore-browser-staging.us-east-1.amazonaws.com"
  api_version: "v1"
  timeout: 45
  max_retries: 3
  retry_delay: 1.5

# Browser Configuration
browser:
  headless: true
  viewport_width: 1920
  viewport_height: 1080
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  page_load_timeout: 45
  element_timeout: 15
  enable_javascript: true
  enable_images: true
  enable_cookies: true

# LlamaIndex Configuration
llamaindex:
  llm_model: "anthropic.claude-3-sonnet-20240229-v1:0"
  vision_model: "anthropic.claude-3-sonnet-20240229-v1:0"
  temperature: 0.1
  max_tokens: 4096
  verbose: false

# CAPTCHA Configuration
captcha:
  enabled: true
  confidence_threshold: 0.8
  max_attempts: 3
  attempt_delay: 2.0
  supported_types:
    - "recaptcha_v2"
    - "recaptcha_v3"
    - "hcaptcha"
    - "text"
    - "image"

# Security Configuration
security:
  sanitize_input: true
  validate_credentials: true
  audit_logging: true
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
  session:
    max_duration: 3600  # 1 hour
    idle_timeout: 1800  # 30 minutes

# Privacy Configuration
privacy:
  pii_detection: true
  pii_mode: "mask"
  data_retention_days: 30
  compliance_reporting: true

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_interval: 60
  error_tracking: true
  health_check_interval: 300
  cloudwatch:
    enabled: true
    namespace: "LlamaIndex/AgentCore/Staging"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  structured: true
  file:
    enabled: true
    path: "logs/staging/llamaindex_agentcore.log"
    max_size: "100MB"
    backup_count: 5
  console:
    enabled: true
    colorize: false

# Development Configuration
development:
  debug: false
  local_browser_fallback: false
  mock_responses: false
  test_data_dir: "tests/data"

# Production Configuration
production:
  optimizations: true
  connection_pool:
    max_connections: 50
    max_keepalive_connections: 10
    keepalive_expiry: 5.0
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30
    expected_exception: "BrowserToolError"