# Configuration template for LlamaIndex-AgentCore Browser Integration
# Copy this file to config.yaml and customize for your environment

# AWS Configuration
aws:
  # AWS region for AgentCore services
  region: "us-east-1"
  
  # AWS credentials (optional - can use IAM roles, environment variables, or AWS CLI)
  # credentials:
  #   access_key_id: "YOUR_ACCESS_KEY_ID"
  #   secret_access_key: "YOUR_SECRET_ACCESS_KEY"
  #   session_token: "YOUR_SESSION_TOKEN"  # Optional for temporary credentials
  
  # AWS profile to use (alternative to explicit credentials)
  profile: "default"

# AgentCore Configuration
agentcore:
  # AgentCore browser tool endpoint
  browser_tool_endpoint: "https://agentcore-browser.us-east-1.amazonaws.com"
  
  # API version
  api_version: "v1"
  
  # Request timeout in seconds
  timeout: 30
  
  # Maximum retry attempts
  max_retries: 3
  
  # Retry delay in seconds
  retry_delay: 1.0

# Browser Configuration
browser:
  # Default browser settings
  headless: true
  viewport_width: 1920
  viewport_height: 1080
  
  # User agent string (optional)
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  
  # Page load timeout in seconds
  page_load_timeout: 30
  
  # Element wait timeout in seconds
  element_timeout: 10
  
  # Enable JavaScript
  enable_javascript: true
  
  # Enable images
  enable_images: true
  
  # Enable cookies
  enable_cookies: true
  
  # Proxy settings (optional)
  # proxy:
  #   http: "http://proxy.example.com:8080"
  #   https: "https://proxy.example.com:8080"

# LlamaIndex Configuration
llamaindex:
  # Default LLM model for text processing
  llm_model: "anthropic.claude-3-sonnet-20240229-v1:0"
  
  # Multi-modal LLM model for CAPTCHA solving
  vision_model: "anthropic.claude-3-sonnet-20240229-v1:0"
  
  # LLM temperature
  temperature: 0.1
  
  # Maximum tokens for responses
  max_tokens: 4096
  
  # Enable verbose logging for agent operations
  verbose: false

# CAPTCHA Configuration
captcha:
  # Enable CAPTCHA detection
  enabled: true
  
  # CAPTCHA detection confidence threshold (0.0 to 1.0)
  confidence_threshold: 0.8
  
  # Maximum attempts to solve CAPTCHA
  max_attempts: 3
  
  # Delay between CAPTCHA attempts in seconds
  attempt_delay: 2.0
  
  # Supported CAPTCHA types
  supported_types:
    - "recaptcha_v2"
    - "recaptcha_v3"
    - "hcaptcha"
    - "text"
    - "image"

# Security Configuration
security:
  # Enable input sanitization
  sanitize_input: true
  
  # Enable credential validation
  validate_credentials: true
  
  # Enable audit logging
  audit_logging: true
  
  # Data encryption settings
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
  
  # Session security
  session:
    max_duration: 3600  # 1 hour in seconds
    idle_timeout: 1800   # 30 minutes in seconds

# Privacy Configuration
privacy:
  # Enable PII detection and scrubbing
  pii_detection: true
  
  # PII scrubbing mode: "mask", "remove", or "hash"
  pii_mode: "mask"
  
  # Data retention policy in days
  data_retention_days: 30
  
  # Enable compliance reporting
  compliance_reporting: true

# Monitoring Configuration
monitoring:
  # Enable performance monitoring
  enabled: true
  
  # Metrics collection interval in seconds
  metrics_interval: 60
  
  # Enable error tracking
  error_tracking: true
  
  # Health check interval in seconds
  health_check_interval: 300
  
  # CloudWatch configuration
  cloudwatch:
    enabled: true
    namespace: "LlamaIndex/AgentCore"
    
  # Custom metrics endpoint (optional)
  # custom_endpoint: "https://metrics.example.com/api/v1/metrics"

# Logging Configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Enable structured logging
  structured: true
  
  # Log file configuration
  file:
    enabled: true
    path: "logs/llamaindex_agentcore.log"
    max_size: "10MB"
    backup_count: 5
  
  # Console logging
  console:
    enabled: true
    colorize: true

# Development Configuration
development:
  # Enable debug mode
  debug: false
  
  # Enable local browser fallback for testing
  local_browser_fallback: false
  
  # Mock AgentCore responses for testing
  mock_responses: false
  
  # Test data directory
  test_data_dir: "tests/data"

# Production Configuration
production:
  # Enable production optimizations
  optimizations: true
  
  # Connection pooling
  connection_pool:
    max_connections: 100
    max_keepalive_connections: 20
    keepalive_expiry: 5.0
  
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  
  # Circuit breaker
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30
    expected_exception: "BrowserToolError"