# Configuration file for LlamaIndex-AgentCore browser tool integration
# This configuration is set up for testing/development environment

# AWS credentials and region configuration
aws_credentials:
  # AWS region where AgentCore services are deployed
  region: us-east-1
  
  # Use AWS profile for development (requires AWS CLI configuration)
  profile: default

# AgentCore service endpoints
# NOTE: These endpoints need to be provided by AWS when AgentCore browser tool is available
agentcore_endpoints:
  # For testing purposes, we'll use placeholder endpoints
  # In production, these would be real AgentCore service endpoints
  base_url: https://agentcore-browser-tool.us-east-1.amazonaws.com
  browser_tool_endpoint: https://agentcore-browser-tool.us-east-1.amazonaws.com/browser-tool
  
  # Development/Testing mode - set to true when AgentCore service is not available
  # This allows the integration to run in test mode without failing
  test_mode: true

# Browser session configuration
browser_config:
  # Run browser in headless mode (no GUI)
  headless: true
  
  # Browser viewport dimensions
  viewport_width: 1920
  viewport_height: 1080
  
  # Timeout settings (in seconds)
  timeout_seconds: 30
  page_load_timeout: 30
  element_timeout: 10
  
  # Browser capabilities
  enable_javascript: true
  enable_images: true
  enable_cookies: true
  enable_local_storage: true
  enable_session_storage: true

# Retry configuration for failed operations
retry_config:
  max_attempts: 3
  base_delay: 1.0
  max_delay: 60.0
  exponential_base: 2.0
  jitter: true
  retryable_errors:
    - timeout
    - network_error
    - rate_limited
    - session_expired

# Logging configuration
logging_config:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  enable_debug: false
  log_agentcore_requests: true
  log_agentcore_responses: false
  max_log_size_mb: 100

# LlamaIndex model configuration
llm_model: anthropic.claude-3-sonnet-20240229-v1:0
vision_model: anthropic.claude-3-sonnet-20240229-v1:0
enable_multi_modal: true

# Security and compliance settings
enable_input_sanitization: true
enable_pii_scrubbing: true
audit_logging: true